---

- name: Add host
  digital_ocean:
    state: present
    command: droplet
    name: mydroplet
    api_token: "{{token}}"
    size_id: 512mb
    id: "{{id}}"
    region_id: ams2
    image_id: ubuntu-14-04-x64
    wait_timeout: 500
  register: my_droplet

- name: Add host to inventory
  add_host:
    name="{{ my_droplet.droplet.ip_address }}"
    groups=digital_ocean 
    dropid= {{ my_droplet.droplet.id }}


